import type { Metadata } from "next";
import "./globals.css";

import { AuthProvider } from '../context/AuthContext'; // 경로에 맞게 수정
import Header from '../shared/components/layout/Header'; // 헤더 컴포넌트 경로에 맞게 수정

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AuthProvider>
          <Header /> {/* Header 컴포넌트가 AuthContext를 사용할 수 있도록 Provider 내부에 위치 */}
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
